name: DarkTeaOps PR Summary
run-name: Summoning DarkTeaOps for PR #${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ollama-runner
    steps:
      - name: 🔮 Checkout Repo
        uses: actions/checkout@v4

      - name: 🫖 Invoke DarkTeaOps
        env:
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEA_API_URL: ${{ gitea.server_url }}/api/v1
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OLLAMA_URL: "http://host.docker.internal:11434/api/generate"
          OLLAMA_MODEL: "gemma3"
        run: |-
          echo "🫖 DarkTeaOps awakens…"
          node <<'EOF'
          require("child_process").spawn("node", [".gitea/workflows/reviewer.js"], {
            stdio: "inherit"
          }).on("exit", code => {
            if (code !== 0) {
              console.error("💀 DarkTeaOps encountered turbulence and plunged deeper into the brew!");
              process.exit(code);
            }
          });
          EOF

